Update the get mapping for signIn request to SignUp request and added…
fulvius31/Polyglot pull request #14
Opened 2023-02-13 04:50 UTC by Sandeep-1-Kumar

added CrossOrigin annotation to facilitate the front end connection and changed the git mapping to post mapping

2023-02-13 18:26 UTC, mepripri commented
As we discussed that Signin will also require POST method call as react doesn't support body in GET method.
I am fine with the change. Approving it.

2023-02-13 18:26 UTC, mepripri approved these changes

2023-02-13 23:49 UTC, Sandeep-1-Kumar commented
I have added all the required code for sprint-1 and i request team to please review and give me the reviews so i can give back the filtered code before sprint-1

2023-02-14 22:16 UTC, fulvius31 commented on Back-End/slu-polyglot/src/main/java/team4/slupolyglot/controller/Controller.java
>              ResponseJson responseJson = new ResponseJson("10404","user already exsists" );
There is a tiny typo `exsists`
We should use an HashMap where the key would be the error code and the value would be the description of that error code. Also, we should avoid the `Magic Number` problem so it would be better to use a final String variable.

2023-02-14 22:17 UTC, fulvius31 commented on Back-End/slu-polyglot/src/main/java/team4/slupolyglot/controller/Controller.java
>              ResponseJson responseJson = new ResponseJson("10404","user already exsists" );
Previous comment is also applicable in the other code part

2023-02-14 22:18 UTC, fulvius31 commented on Back-End/slu-polyglot/src/main/java/team4/slupolyglot/model/RequestJsonSignUpMapping.java
We should use just one new line instead of multiple

2023-02-14 22:22 UTC, fulvius31 commented on Back-End/slu-polyglot/src/main/java/team4/slupolyglot/controller/Controller.java
>              {
We should use the code style we agreed. The curly bracket should go at the end of the line.

This one should be applied in all part of code where is not.

2023-02-14 22:26 UTC, fulvius31 requested changes
You did a great job. I've mentioned just a couple of things on the code.
It's more about code style and magic number

2023-02-17 17:51 UTC, Sandeep-1-Kumar commented on Back-End/slu-polyglot/src/main/java/team4/slupolyglot/controller/Controller.java
> +                userRepository.save(new Player(requestJsonSignUpMapping.getEmail(),requestJsonSignUpMapping.getName(),"0",requestJsonSignUpMapping.getPassword()));
Thank you for the suggestion, I have corrected the code , IN spite of long lines I had split the long lines and the code looks crisp now@fulvius31

2023-02-17 17:53 UTC, Sandeep-1-Kumar commented on Back-End/slu-polyglot/src/main/java/team4/slupolyglot/controller/Controller.java
>              ResponseJson responseJson = new ResponseJson("10404","user already exsists" );
Yes, That's a good suggestion which helped me to decrease the extra unused java classes. I had corrected code accordingly.

2023-02-17 17:54 UTC, Sandeep-1-Kumar commented on Back-End/slu-polyglot/src/main/java/team4/slupolyglot/controller/Controller.java
>              {
Yes , I have corrected it ,Thanks again.

2023-02-17 17:55 UTC, Sandeep-1-Kumar commented on Back-End/slu-polyglot/src/main/java/team4/slupolyglot/model/RequestJsonSignUpMapping.java
Can you please give me a more descriptive sugesstion.

2023-02-17 18:03 UTC, fulvius31 commented on Back-End/slu-polyglot/src/main/java/team4/slupolyglot/model/RequestJsonSignUpMapping.java
It was just a "code style thing" you have put multiple new lines instead of just one

2023-02-17 18:13 UTC, Sandeep-1-Kumar commented on Back-End/slu-polyglot/src/main/java/team4/slupolyglot/model/RequestJsonSignUpMapping.java
Got it ,Thanks @fulvius31

2023-02-17 18:13 UTC, fulvius31 commented on Back-End/slu-polyglot/src/main/java/team4/slupolyglot/controller/Controller.java
> +                    response = new HashMap<>();
We should not use the hashmap for response but we should initialize publicly an HashMap just for the fields `errorCode` and `errorCodeDescription` so we can use everywhere in the code.
Something like this:
```
Map<String, String> erroCodeMap = new HashMap<String, String>() {{
    put("10200", "Player sucessfully validated");
    put("10404", "...");
    ...
}};
```

2023-02-17 18:14 UTC, fulvius31 commented on Back-End/slu-polyglot/src/main/java/team4/slupolyglot/controller/Controller.java
> +                    response = new HashMap<>();
And then we can use the hashmap to get the error code and its value (description)

2023-02-17 19:54 UTC, Sandeep-1-Kumar commented
Please review the updated code and accept the pull request @fulvius31

2023-02-18 00:10 UTC, Sandeep-1-Kumar commented on Back-End/slu-polyglot/src/main/java/team4/slupolyglot/controller/Controller.java
> +                    response = new HashMap<>();
I had implemented and updated please verify and accept pull request.

2023-02-21 23:34 UTC, merged