Game 3
fulvius31/Polyglot pull request #62
Opened 2023-04-16 03:06 UTC by Sandeep-1-Kumar

updated imperative tense handler for swahili algorithm

2023-04-16 03:42 UTC, fulvius31 commented on Back-End/slu-polyglot/src/main/java/team4/slupolyglot/model/EnglishSwahiliTranslation.java
> +            {
The `{` should go at the end of the if statement 
can you double check also in all the other part of this commit?

2023-04-16 03:45 UTC, fulvius31 commented on Back-End/slu-polyglot/src/main/java/team4/slupolyglot/model/SyllableCounter.java
> +            return 3;
we can beautify it afterwards. Btw, we should not use `magic numbers` so can you explain in a variable what is 3? thanks

2023-04-16 03:47 UTC, fulvius31 requested changes
Thanks for your work!

I wrote some comments. Other than that, we need to do refactoring in the next sprint.

Did all the tests passed?

2023-04-17 02:05 UTC, Sandeep-1-Kumar commented on Back-End/slu-polyglot/src/main/java/team4/slupolyglot/model/SyllableCounter.java
> +            return 3;
I have removed that part of code and added a modified version of it. Please check in the next commit change. Thank you.

2023-04-17 02:13 UTC, fulvius31 commented on Back-End/slu-polyglot/src/test/java/team4/slupolyglot/SwahiliTests.java
> +    BufferedReader reader = new BufferedReader(new FileReader("C:\\Users\\sande\\Desktop\\PSD\\git_ultra_pro\\Polyglot\\Back-End\\slu-polyglot\\src\\test\\java\\team4\\slupolyglot\\resources\\testdis
To import the tsv file, take inspiration from 
https://github.com/fulvius31/Polyglot/blob/develop/Back-End/slu-polyglot/src/test/java/team4/slupolyglot/TranslationTests.java

the file has to be copied on https://github.com/fulvius31/Polyglot/tree/develop/Back-End/slu-polyglot/src/main/resources folder

2023-04-17 02:14 UTC, fulvius31 requested changes
Thanks for the code provided!

Just a small change on the test file so the test can run in every machine

2023-04-17 02:26 UTC, merged

2023-04-17 02:27 UTC, Sandeep-1-Kumar commented
> Thanks for the code provided!
> 
> Just a small change on the test file so the test can run in every machine

Yes thanks for letting me know brother i have updated and pushed.